server:
  port: 30050

eureka:
  instance:
    prefer-ip-address: true
    ip-address: "${HOST_IP}"

spring:
    application:
      name: log-service
    jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      generate-ddl: true
      show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
