server:
  port: 30050

eureka:
  instance:
    prefer-ip-address: true
    ip-address: "${HOST_IP}"

spring:
    application:
      name: log-service
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
